name: remote ssh command
on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run remote ssh command
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USERNAME }}
        host: ${{ secrets.HOST }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd vercel-next14-learning
          git pull origin master
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          npm --help
          npm install
          npm run build

